# Generated by Django 4.0.4 on 2022-06-01 22:17

from django.db import migrations, models
import whatsapp.utils.slug


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, default=whatsapp.utils.slug.gen_slug, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
